name = "day01"
description = "Advent of Ada - Day 1"
version = "0.1.0-dev"

authors = ["Daniel Larraz"]
maintainers = ["Daniel Larraz <daniel-larraz@users.noreply.github.com>"]
maintainers-logins = ["daniel-larraz"]

executables = ["day01"]
[[depends-on]]
gnatprove = "^13.2.1"
