name = "day03"
description = "Advent of Ada - Day 3"
version = "0.1.0-dev"

authors = ["Daniel Larraz"]
maintainers = ["Daniel Larraz <daniel-larraz@users.noreply.github.com>"]
maintainers-logins = ["daniel-larraz"]

executables = ["day03"]

[build-switches]
"*".ada_version = "Ada2022"

[[depends-on]]
gnatprove = "^14.1.1"
aoc = "*"

[[pins]]
aoc = { path='../aoc' }
